application: channel-api
version: 1
runtime: go
api_version: 2

inbound_services:
- channel_presence

handlers:
- url: /.*
  script: _go_app

- url: /jquery.js
  static_files: jquery.js
  upload: jquery.js

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  mime_type: image/x-icon
